remote_theme: thelehhman/texture
title: Navak Ray's Homepage
author: Navak Ray
email: 2981975967@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Navak Ray
  tagline: One fine day,everything you insit on,will embrace you yin turn.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter:
    github:
    linkedIn: 
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
